import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { LogIn, UserPlus } from "lucide-react";
import { PageShell } from "@/components/PageShell";

export const Route = createFileRoute("/admin-acces")({\n  head: () => ({\n    meta: [\n      { title: "Espace Administrateur - CampusLink" },\n      {\n        name: "description",\n        content: "Inscription et connexion pour les administrateurs d'établissement",\n      },\n    ],\n  }),\n  component: AdminAccess,\n});

function AdminAccess() {\n  const [activeTab, setActiveTab] = useState<"login" | "signup">("login");

  return (\n    <div className="bg-paper min-h-screen text-foreground">\n      <div className="mx-auto max-w-4xl px-6 py-10">\n        <Link to="/" className="btn-bf-outline mb-8">\n          Retour à l'accueil\n        </Link>\n        <div className="kente-stripe mb-8 h-1.5 w-24 rounded-full" />\n        <h1 className="mb-8 text-4xl font-bold text-gradient-bf">Espace Administrateur</h1>\n\n        {/* Tabs */}\n        <div className="mb-8 flex gap-4 border-b border-input">\n          <button\n            onClick={() => setActiveTab("login")}\n            className={`pb-4 font-medium transition ${ \n              activeTab === "login"\n                ? "border-b-2 border-primary text-primary"\n                : "text-muted-foreground hover:text-foreground"\n            }`}\n          >\n            <LogIn className="mb-1 inline-block h-4 w-4" />\n            {" "} Se connecter\n          </button>\n          <button\n            onClick={() => setActiveTab("signup")}\n            className={`pb-4 font-medium transition ${ \n              activeTab === "signup"\n                ? "border-b-2 border-primary text-primary"\n                : "text-muted-foreground hover:text-foreground"\n            }`}\n          >\n            <UserPlus className="mb-1 inline-block h-4 w-4" />\n            {" "} S'inscrire\n          </button>\n        </div>\n\n        {/* Content */}\n        <div className="card-glass rounded-2xl p-8">\n          {activeTab === "login" && (\n            <div className="mx-auto max-w-md">\n              <p className="mb-6 text-sm text-muted-foreground">\n                Connectez-vous avec vos identifiants d'administrateur.\n              </p>\n              <Link\n                to="/admin/connexion"\n                className="btn-bf-primary w-full block text-center"\n              >\n                Accéder à la connexion\n              </Link>\n            </div>\n          )}\n\n          {activeTab === "signup" && (\n            <div className="mx-auto max-w-md">\n              <p className="mb-6 text-sm text-muted-foreground">\n                Inscrivez-vous en tant qu'administrateur d'établissement.\n              </p>\n              <Link\n                to="/admin/inscription"\n                className="btn-bf-primary w-full block text-center"\n              >\n                Accéder à l'inscription\n              </Link>\n            </div>\n          )}\n        </div>\n      </div>\n    </div>\n  );\n}
