/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as DevenirPartenaireRouteImport } from './routes/devenir-partenaire'
import { Route as CoursEnLigneRouteImport } from './routes/cours-en-ligne'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtudiantInscriptionRouteImport } from './routes/etudiant.inscription'
import { Route as EtudiantConnexionRouteImport } from './routes/etudiant.connexion'
import { Route as AdminInscriptionRouteImport } from './routes/admin.inscription'
import { Route as AdminConnexionRouteImport } from './routes/admin.connexion'

const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirPartenaireRoute = DevenirPartenaireRouteImport.update({
  id: '/devenir-partenaire',
  path: '/devenir-partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursEnLigneRoute = CoursEnLigneRouteImport.update({
  id: '/cours-en-ligne',
  path: '/cours-en-ligne',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantInscriptionRoute = EtudiantInscriptionRouteImport.update({
  id: '/etudiant/inscription',
  path: '/etudiant/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantConnexionRoute = EtudiantConnexionRouteImport.update({
  id: '/etudiant/connexion',
  path: '/etudiant/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscriptionRoute = AdminInscriptionRouteImport.update({
  id: '/admin/inscription',
  path: '/admin/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin/connexion',
  path: '/admin/connexion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cours-en-ligne': typeof CoursEnLigneRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/inscription': typeof AdminInscriptionRoute
  '/etudiant/connexion': typeof EtudiantConnexionRoute
  '/etudiant/inscription': typeof EtudiantInscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cours-en-ligne': typeof CoursEnLigneRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/inscription': typeof AdminInscriptionRoute
  '/etudiant/connexion': typeof EtudiantConnexionRoute
  '/etudiant/inscription': typeof EtudiantInscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cours-en-ligne': typeof CoursEnLigneRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/inscription': typeof AdminInscriptionRoute
  '/etudiant/connexion': typeof EtudiantConnexionRoute
  '/etudiant/inscription': typeof EtudiantInscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cours-en-ligne'
    | '/devenir-partenaire'
    | '/fonctionnalites'
    | '/politique-confidentialite'
    | '/admin/connexion'
    | '/admin/inscription'
    | '/etudiant/connexion'
    | '/etudiant/inscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cours-en-ligne'
    | '/devenir-partenaire'
    | '/fonctionnalites'
    | '/politique-confidentialite'
    | '/admin/connexion'
    | '/admin/inscription'
    | '/etudiant/connexion'
    | '/etudiant/inscription'
  id:
    | '__root__'
    | '/'
    | '/cours-en-ligne'
    | '/devenir-partenaire'
    | '/fonctionnalites'
    | '/politique-confidentialite'
    | '/admin/connexion'
    | '/admin/inscription'
    | '/etudiant/connexion'
    | '/etudiant/inscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursEnLigneRoute: typeof CoursEnLigneRoute
  DevenirPartenaireRoute: typeof DevenirPartenaireRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  AdminConnexionRoute: typeof AdminConnexionRoute
  AdminInscriptionRoute: typeof AdminInscriptionRoute
  EtudiantConnexionRoute: typeof EtudiantConnexionRoute
  EtudiantInscriptionRoute: typeof EtudiantInscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-partenaire': {
      id: '/devenir-partenaire'
      path: '/devenir-partenaire'
      fullPath: '/devenir-partenaire'
      preLoaderRoute: typeof DevenirPartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours-en-ligne': {
      id: '/cours-en-ligne'
      path: '/cours-en-ligne'
      fullPath: '/cours-en-ligne'
      preLoaderRoute: typeof CoursEnLigneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/inscription': {
      id: '/etudiant/inscription'
      path: '/etudiant/inscription'
      fullPath: '/etudiant/inscription'
      preLoaderRoute: typeof EtudiantInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/connexion': {
      id: '/etudiant/connexion'
      path: '/etudiant/connexion'
      fullPath: '/etudiant/connexion'
      preLoaderRoute: typeof EtudiantConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscription': {
      id: '/admin/inscription'
      path: '/admin/inscription'
      fullPath: '/admin/inscription'
      preLoaderRoute: typeof AdminInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connexion': {
      id: '/admin/connexion'
      path: '/admin/connexion'
      fullPath: '/admin/connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursEnLigneRoute: CoursEnLigneRoute,
  DevenirPartenaireRoute: DevenirPartenaireRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  AdminConnexionRoute: AdminConnexionRoute,
  AdminInscriptionRoute: AdminInscriptionRoute,
  EtudiantConnexionRoute: EtudiantConnexionRoute,
  EtudiantInscriptionRoute: EtudiantInscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
