/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as DevenirPartenaireRouteImport } from './routes/devenir-partenaire'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtudiantInscriptionRouteImport } from './routes/etudiant/inscription'
import { Route as EtudiantDashboardRouteImport } from './routes/etudiant/dashboard'
import { Route as EtudiantConnexionRouteImport } from './routes/etudiant/connexion'
import { Route as AdminInscriptionRouteImport } from './routes/admin/inscription'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConnexionRouteImport } from './routes/admin/connexion'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirPartenaireRoute = DevenirPartenaireRouteImport.update({
  id: '/devenir-partenaire',
  path: '/devenir-partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantInscriptionRoute = EtudiantInscriptionRouteImport.update({
  id: '/etudiant/inscription',
  path: '/etudiant/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantDashboardRoute = EtudiantDashboardRouteImport.update({
  id: '/etudiant/dashboard',
  path: '/etudiant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantConnexionRoute = EtudiantConnexionRouteImport.update({
  id: '/etudiant/connexion',
  path: '/etudiant/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscriptionRoute = AdminInscriptionRouteImport.update({
  id: '/admin/inscription',
  path: '/admin/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin/connexion',
  path: '/admin/connexion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inscription': typeof AdminInscriptionRoute
  '/etudiant/connexion': typeof EtudiantConnexionRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
  '/etudiant/inscription': typeof EtudiantInscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inscription': typeof AdminInscriptionRoute
  '/etudiant/connexion': typeof EtudiantConnexionRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
  '/etudiant/inscription': typeof EtudiantInscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devenir-partenaire': typeof DevenirPartenaireRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inscription': typeof AdminInscriptionRoute
  '/etudiant/connexion': typeof EtudiantConnexionRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
  '/etudiant/inscription': typeof EtudiantInscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devenir-partenaire'
    | '/fonctionnalites'
    | '/politique-confidentialite'
    | '/super-admin'
    | '/admin/connexion'
    | '/admin/dashboard'
    | '/admin/inscription'
    | '/etudiant/connexion'
    | '/etudiant/dashboard'
    | '/etudiant/inscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devenir-partenaire'
    | '/fonctionnalites'
    | '/politique-confidentialite'
    | '/super-admin'
    | '/admin/connexion'
    | '/admin/dashboard'
    | '/admin/inscription'
    | '/etudiant/connexion'
    | '/etudiant/dashboard'
    | '/etudiant/inscription'
  id:
    | '__root__'
    | '/'
    | '/devenir-partenaire'
    | '/fonctionnalites'
    | '/politique-confidentialite'
    | '/super-admin'
    | '/admin/connexion'
    | '/admin/dashboard'
    | '/admin/inscription'
    | '/etudiant/connexion'
    | '/etudiant/dashboard'
    | '/etudiant/inscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevenirPartenaireRoute: typeof DevenirPartenaireRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  SuperAdminRoute: typeof SuperAdminRoute
  AdminConnexionRoute: typeof AdminConnexionRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInscriptionRoute: typeof AdminInscriptionRoute
  EtudiantConnexionRoute: typeof EtudiantConnexionRoute
  EtudiantDashboardRoute: typeof EtudiantDashboardRoute
  EtudiantInscriptionRoute: typeof EtudiantInscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-partenaire': {
      id: '/devenir-partenaire'
      path: '/devenir-partenaire'
      fullPath: '/devenir-partenaire'
      preLoaderRoute: typeof DevenirPartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/inscription': {
      id: '/etudiant/inscription'
      path: '/etudiant/inscription'
      fullPath: '/etudiant/inscription'
      preLoaderRoute: typeof EtudiantInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/dashboard': {
      id: '/etudiant/dashboard'
      path: '/etudiant/dashboard'
      fullPath: '/etudiant/dashboard'
      preLoaderRoute: typeof EtudiantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/connexion': {
      id: '/etudiant/connexion'
      path: '/etudiant/connexion'
      fullPath: '/etudiant/connexion'
      preLoaderRoute: typeof EtudiantConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscription': {
      id: '/admin/inscription'
      path: '/admin/inscription'
      fullPath: '/admin/inscription'
      preLoaderRoute: typeof AdminInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connexion': {
      id: '/admin/connexion'
      path: '/admin/connexion'
      fullPath: '/admin/connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevenirPartenaireRoute: DevenirPartenaireRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  SuperAdminRoute: SuperAdminRoute,
  AdminConnexionRoute: AdminConnexionRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInscriptionRoute: AdminInscriptionRoute,
  EtudiantConnexionRoute: EtudiantConnexionRoute,
  EtudiantDashboardRoute: EtudiantDashboardRoute,
  EtudiantInscriptionRoute: EtudiantInscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
